import { Post } from "./types";

export const mockPosts: Post[] = [
  {
    id: "1",
    title: "CoC 7판 단편 시나리오 - 잊혀진 서재",
    gameSystem: "coc7",
    playMode: "online",
    experienceLevel: "newbie",
    maxPlayers: 4,
    currentPlayers: 2,
    description:
      "입문자 환영! 가볍게 즐길 수 있는 2~3시간짜리 단편 시나리오입니다. 1920년대 미국을 배경으로 한 미스터리 조사물이며, 키퍼가 친절하게 안내해드립니다. 디스코드 음성 채팅으로 진행합니다.",
    schedule: "매주 토요일 오후 3시",
    authorName: "키퍼_민수",
    createdAt: "2026-03-28T10:00:00Z",
    isRecruiting: true,
  },
  {
    id: "2",
    title: "D&D 5e 캠페인 - 잃어버린 광산",
    gameSystem: "dnd5e",
    playMode: "offline",
    experienceLevel: "intermediate",
    maxPlayers: 5,
    currentPlayers: 3,
    description:
      "서울 홍대 보드게임카페에서 진행하는 D&D 5e 캠페인입니다. 매주 일요일 오후에 만나서 4시간 정도 플레이합니다. 기본 룰북은 숙지하고 오시면 좋습니다.",
    schedule: "매주 일요일 오후 1시",
    region: "서울 마포구 홍대입구",
    authorName: "DM_하늘",
    createdAt: "2026-03-27T15:30:00Z",
    isRecruiting: true,
  },
  {
    id: "3",
    title: "인세인 - 밀실의 악몽",
    gameSystem: "insane",
    playMode: "online",
    experienceLevel: "veteran",
    maxPlayers: 4,
    currentPlayers: 4,
    description:
      "PvP 요소가 강한 인세인 시나리오입니다. 서로를 의심하며 자신의 비밀을 지켜야 합니다. 인세인 경험자 우대합니다. 예상 플레이 시간 4~5시간.",
    schedule: "3월 30일(일) 오후 7시",
    authorName: "GM_다크",
    createdAt: "2026-03-26T20:00:00Z",
    isRecruiting: false,
  },
  {
    id: "4",
    title: "CoC 7판 장편 캠페인 - 마스크",
    gameSystem: "coc7",
    playMode: "both",
    experienceLevel: "any",
    maxPlayers: 6,
    currentPlayers: 1,
    description:
      "유명한 장편 캠페인 시나리오를 함께할 분을 모집합니다. 온라인과 오프라인 격주로 진행할 예정이며, 장기간(3~4개월) 함께하실 수 있는 분을 찾습니다.",
    schedule: "격주 토요일 오후 2시",
    region: "서울 강남 / 온라인 병행",
    authorName: "키퍼_제이",
    createdAt: "2026-03-25T09:00:00Z",
    isRecruiting: true,
  },
  {
    id: "5",
    title: "D&D 5e 원샷 - 용의 둥지",
    gameSystem: "dnd5e",
    playMode: "online",
    experienceLevel: "newbie",
    maxPlayers: 4,
    currentPlayers: 0,
    description:
      "D&D 처음이신 분도 환영합니다! 캐릭터 시트 작성부터 도와드립니다. 가볍게 한 번 해보고 싶은 분들을 위한 원샷 세션입니다.",
    schedule: "4월 5일(토) 오후 2시",
    authorName: "DM_루나",
    createdAt: "2026-03-24T14:00:00Z",
    isRecruiting: true,
  },
];
